# Generated by Django 4.1.7 on 2023-04-01 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_codingskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coding_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.codingskill')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.tool')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('role_responsibilities', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('close', 'Close')], max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('technology_used', models.ManyToManyField(to='resume.technology')),
            ],
        ),
    ]
