# Generated by Django 4.1.7 on 2023-04-01 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_technology_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='coding_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.codingskill'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.tool'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
