# Generated by Django 4.1.7 on 2023-04-12 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='deleted',
            new_name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='coding',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_status',
        ),
        migrations.AddField(
            model_name='employee',
            name='coding_skills',
            field=models.ManyToManyField(to='resume.codingskill'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_current_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='professional_summary',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='tools',
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.designation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tools',
            field=models.ManyToManyField(to='resume.tool'),
        ),
    ]
