# Generated by Django 4.1.7 on 2023-04-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_designation_rename_deleted_employee_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('technology_used', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('role_responsibilities', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flag', models.BooleanField(default=1)),
            ],
        ),
    ]
