# Generated by Django 4.1.7 on 2023-04-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mapped_project',
            field=models.ManyToManyField(to='resume.projects'),
        ),
    ]
