# Generated by Django 4.1.7 on 2023-04-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='flag',
            field=models.BooleanField(default=1),
        ),
    ]
