# Generated by Django 4.1.7 on 2023-04-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_technology_flag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
