# Generated by Django 4.1.5 on 2023-05-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_employee_eamil_employee_linkedin_employee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='eamil',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
